In [1]:
import pandas as pd

In [4]:
nba = pd.read_csv('nba.csv')

In [6]:
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [7]:
nba.tail(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
nba.index

RangeIndex(start=0, stop=458, step=1)

In [9]:
nba.values

array([['Avery Bradley', 'Boston Celtics', 0.0, ..., 180.0, 'Texas',
        7730337.0],
       ['Jae Crowder', 'Boston Celtics', 99.0, ..., 235.0, 'Marquette',
        6796117.0],
       ['John Holland', 'Boston Celtics', 30.0, ..., 205.0,
        'Boston University', nan],
       ...,
       ['Tibor Pleiss', 'Utah Jazz', 21.0, ..., 256.0, nan, 2900000.0],
       ['Jeff Withey', 'Utah Jazz', 24.0, ..., 231.0, 'Kansas', 947276.0],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=object)

In [10]:
nba.shape

(458, 9)

In [11]:
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [12]:
nba.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [13]:
nba.axes

[RangeIndex(start=0, stop=458, step=1),
 Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
        'College', 'Salary'],
       dtype='object')]

In [15]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null float64
Position    457 non-null object
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     373 non-null object
Salary      446 non-null float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [16]:
nba.get_dtype_counts()

float64    4
object     5
dtype: int64

In [17]:
rev = pd.read_csv('revenue.csv', index_col = 'Date')
rev.head(3)

        New York  Los Angeles  Miami
Date
1/1/16       985          122    499
1/2/16       738          788    534
1/3/16        14           20    933

In [18]:
rev.sum()

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [19]:
rev.sum(axis=1)

Date
1/1/16     1606
1/2/16     2060
1/3/16      967
1/4/16     2519
1/5/16      438
1/6/16     1935
1/7/16     1234
1/8/16     2313
1/9/16     2623
1/10/16     555
dtype: int64

In [20]:
nba.Name
#Problem is it only works when our column name does not have 
#spaces so generally not good

0                Avery Bradley
1                  Jae Crowder
2                 John Holland
3                  R.J. Hunter
4                Jonas Jerebko
5                 Amir Johnson
6                Jordan Mickey
7                 Kelly Olynyk
8                 Terry Rozier
9                 Marcus Smart
10             Jared Sullinger
11               Isaiah Thomas
12                 Evan Turner
13                 James Young
14                Tyler Zeller
15            Bojan Bogdanovic
16                Markel Brown
17             Wayne Ellington
18     Rondae Hollis-Jefferson
19                Jarrett Jack
20              Sergey Karasev
21             Sean Kilpatrick
22                Shane Larkin
23                 Brook Lopez
24            Chris McCullough
25                 Willie Reed
26             Thomas Robinson
27                  Henry Sims
28                Donald Sloan
29              Thaddeus Young
                ...
428            Al-Farouq Aminu
429            Pat Connaughton
430               Allen Crabbe
431                   Ed Davis
432           Maurice Harkless
433           Gerald Henderson
434                Chris Kaman
435             Meyers Leonard
436             Damian Lillard
437              C.J. McCollum
438               Luis Montero
439              Mason Plumlee
440              Brian Roberts
441                Noah Vonleh
442              Trevor Booker
443                 Trey Burke
444                 Alec Burks
445                 Dante Exum
446             Derrick Favors
447                Rudy Gobert
448             Gordon Hayward
449                Rodney Hood
450                 Joe Ingles
451              Chris Johnson
452                 Trey Lyles
453               Shelvin Mack
454                  Raul Neto
455               Tibor Pleiss
456                Jeff Withey
457                        NaN
Name: Name, Length: 458, dtype: object

In [21]:
nba['Name']

0                Avery Bradley
1                  Jae Crowder
2                 John Holland
3                  R.J. Hunter
4                Jonas Jerebko
5                 Amir Johnson
6                Jordan Mickey
7                 Kelly Olynyk
8                 Terry Rozier
9                 Marcus Smart
10             Jared Sullinger
11               Isaiah Thomas
12                 Evan Turner
13                 James Young
14                Tyler Zeller
15            Bojan Bogdanovic
16                Markel Brown
17             Wayne Ellington
18     Rondae Hollis-Jefferson
19                Jarrett Jack
20              Sergey Karasev
21             Sean Kilpatrick
22                Shane Larkin
23                 Brook Lopez
24            Chris McCullough
25                 Willie Reed
26             Thomas Robinson
27                  Henry Sims
28                Donald Sloan
29              Thaddeus Young
                ...
428            Al-Farouq Aminu
429            Pat Connaughton
430               Allen Crabbe
431                   Ed Davis
432           Maurice Harkless
433           Gerald Henderson
434                Chris Kaman
435             Meyers Leonard
436             Damian Lillard
437              C.J. McCollum
438               Luis Montero
439              Mason Plumlee
440              Brian Roberts
441                Noah Vonleh
442              Trevor Booker
443                 Trey Burke
444                 Alec Burks
445                 Dante Exum
446             Derrick Favors
447                Rudy Gobert
448             Gordon Hayward
449                Rodney Hood
450                 Joe Ingles
451              Chris Johnson
452                 Trey Lyles
453               Shelvin Mack
454                  Raul Neto
455               Tibor Pleiss
456                Jeff Withey
457                        NaN
Name: Name, Length: 458, dtype: object

In [24]:
#Extracting multiple columns
nba[['Name', 'Team']]

                        Name                    Team
0              Avery Bradley          Boston Celtics
1                Jae Crowder          Boston Celtics
2               John Holland          Boston Celtics
3                R.J. Hunter          Boston Celtics
4              Jonas Jerebko          Boston Celtics
5               Amir Johnson          Boston Celtics
6              Jordan Mickey          Boston Celtics
7               Kelly Olynyk          Boston Celtics
8               Terry Rozier          Boston Celtics
9               Marcus Smart          Boston Celtics
10           Jared Sullinger          Boston Celtics
11             Isaiah Thomas          Boston Celtics
12               Evan Turner          Boston Celtics
13               James Young          Boston Celtics
14              Tyler Zeller          Boston Celtics
15          Bojan Bogdanovic           Brooklyn Nets
16              Markel Brown           Brooklyn Nets
17           Wayne Ellington           Brooklyn Nets
18   Rondae Hollis-Jefferson           Brooklyn Nets
19              Jarrett Jack           Brooklyn Nets
20            Sergey Karasev           Brooklyn Nets
21           Sean Kilpatrick           Brooklyn Nets
22              Shane Larkin           Brooklyn Nets
23               Brook Lopez           Brooklyn Nets
24          Chris McCullough           Brooklyn Nets
25               Willie Reed           Brooklyn Nets
26           Thomas Robinson           Brooklyn Nets
27                Henry Sims           Brooklyn Nets
28              Donald Sloan           Brooklyn Nets
29            Thaddeus Young           Brooklyn Nets
..                       ...                     ...
428          Al-Farouq Aminu  Portland Trail Blazers
429          Pat Connaughton  Portland Trail Blazers
430             Allen Crabbe  Portland Trail Blazers
431                 Ed Davis  Portland Trail Blazers
432         Maurice Harkless  Portland Trail Blazers
433         Gerald Henderson  Portland Trail Blazers
434              Chris Kaman  Portland Trail Blazers
435           Meyers Leonard  Portland Trail Blazers
436           Damian Lillard  Portland Trail Blazers
437            C.J. McCollum  Portland Trail Blazers
438             Luis Montero  Portland Trail Blazers
439            Mason Plumlee  Portland Trail Blazers
440            Brian Roberts  Portland Trail Blazers
441              Noah Vonleh  Portland Trail Blazers
442            Trevor Booker               Utah Jazz
443               Trey Burke               Utah Jazz
444               Alec Burks               Utah Jazz
445               Dante Exum               Utah Jazz
446           Derrick Favors               Utah Jazz
447              Rudy Gobert               Utah Jazz
448           Gordon Hayward               Utah Jazz
449              Rodney Hood               Utah Jazz
450               Joe Ingles               Utah Jazz
451            Chris Johnson               Utah Jazz
452               Trey Lyles               Utah Jazz
453             Shelvin Mack               Utah Jazz
454                Raul Neto               Utah Jazz
455             Tibor Pleiss               Utah Jazz
456              Jeff Withey               Utah Jazz
457                      NaN                     NaN

[458 rows x 2 columns]

In [25]:
#Adding new column to existing dataframe
nba['Sport'] = 'Basketball'

In [26]:
nba.head(4)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball

In [27]:
nba.insert(3, column = 'Country', value='USA')

In [28]:
nba.head(4)

,Name,Team,Number,Country,Position,Age,Height,Weight,College,Salary,Sport
0,Avery Bradley,Boston Celtics,0.0,USA,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball
1,Jae Crowder,Boston Celtics,99.0,USA,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball
2,John Holland,Boston Celtics,30.0,USA,SG,27.0,6-5,205.0,Boston University,NaN,Basketball
3,R.J. Hunter,Boston Celtics,28.0,USA,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball

In [29]:
nba['Age'].add(2)

0      27.0
1      27.0
2      29.0
3      24.0
4      31.0
5      31.0
6      23.0
7      27.0
8      24.0
9      24.0
10     26.0
11     29.0
12     29.0
13     22.0
14     28.0
15     29.0
16     26.0
17     30.0
18     23.0
19     34.0
20     24.0
21     28.0
22     25.0
23     30.0
24     23.0
25     28.0
26     27.0
27     28.0
28     30.0
29     29.0
       ...
428    27.0
429    25.0
430    26.0
431    29.0
432    25.0
433    30.0
434    36.0
435    26.0
436    27.0
437    26.0
438    25.0
439    28.0
440    32.0
441    22.0
442    30.0
443    25.0
444    26.0
445    22.0
446    26.0
447    25.0
448    28.0
449    25.0
450    30.0
451    28.0
452    22.0
453    28.0
454    26.0
455    28.0
456    28.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [34]:
nba.dropna(subset = ['Salary', 'College'])

,Name,Team,Number,Country,Position,Age,Height,Weight,College,Salary,Sport
0,Avery Bradley,Boston Celtics,0.0,USA,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball
1,Jae Crowder,Boston Celtics,99.0,USA,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball
3,R.J. Hunter,Boston Celtics,28.0,USA,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball
6,Jordan Mickey,Boston Celtics,55.0,USA,PF,21.0,6-8,235.0,LSU,1170960.0,Basketball
7,Kelly Olynyk,Boston Celtics,41.0,USA,C,25.0,7-0,238.0,Gonzaga,2165160.0,Basketball
8,Terry Rozier,Boston Celtics,12.0,USA,PG,22.0,6-2,190.0,Louisville,1824360.0,Basketball
9,Marcus Smart,Boston Celtics,36.0,USA,PG,22.0,6-4,220.0,Oklahoma State,3431040.0,Basketball
10,Jared Sullinger,Boston Celtics,7.0,USA,C,24.0,6-9,260.0,Ohio State,2569260.0,Basketball
11,Isaiah Thomas,Boston Celtics,4.0,USA,PG,27.0,5-9,185.0,Washington,6912869.0,Basketball
12,Evan Turner,Boston Celtics,11.0,USA,SG,27.0,6-7,220.0,Ohio State,3425510.0,Basketball
13,James Young,Boston Celtics,13.0,USA,SG,20.0,6-6,215.0,Kentucky,1749840.0,Basketball
14,Tyler Zeller,Boston Celtics,44.0,USA,C,26.0,7-0,253.0,North Carolina,2616975.0,Basketball
16,Markel Brown,Brooklyn Nets,22.0,USA,SG,24.0,6-3,190.0,Oklahoma State,845059.0,Basketball
17,Wayne Ellington,Brooklyn Nets,21.0,USA,SG,28.0,6-4,200.0,North Carolina,1500000.0,Basketball
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,USA,SG,21.0,6-7,220.0,Arizona,1335480.0,Basketball
19,Jarrett Jack,Brooklyn Nets,2.0,USA,PG,32.0,6-3,200.0,Georgia Tech,6300000.0,Basketball
21,Sean Kilpatrick,Brooklyn Nets,6.0,USA,SG,26.0,6-4,219.0,Cincinnati,134215.0,Basketball
22,Shane Larkin,Brooklyn Nets,0.0,USA,PG,23.0,5-11,175.0,Miami (FL),1500000.0,Basketball
23,Brook Lopez,Brooklyn Nets,11.0,USA,C,28.0,7-0,275.0,Stanford,19689000.0,Basketball
24,Chris McCullough,Brooklyn Nets,1.0,USA,PF,21.0,6-11,200.0,Syracuse,1140240.0,Basketball
25,Willie Reed,Brooklyn Nets,33.0,USA,PF,26.0,6-10,220.0,Saint Louis,947276.0,Basketball
26,Thomas Robinson,Brooklyn Nets,41.0,USA,PF,25.0,6-10,237.0,Kansas,981348.0,Basketball
27,Henry Sims,Brooklyn Nets,14.0,USA,C,26.0,6-10,248.0,Georgetown,947276.0,Basketball
28,Donald Sloan,Brooklyn Nets,15.0,USA,PG,28.0,6-3,205.0,Texas A&M,947276.0,Basketball
29,Thaddeus Young,Brooklyn Nets,30.0,USA,PF,27.0,6-8,221.0,Georgia Tech,11235955.0,Basketball
30,Arron Afflalo,New York Knicks,4.0,USA,SG,30.0,6-5,210.0,UCLA,8000000.0,Basketball
31,Lou Amundson,New York Knicks,17.0,USA,PF,33.0,6-9,220.0,UNLV,1635476.0,Basketball
33,Carmelo Anthony,New York Knicks,7.0,USA,SF,32.0,6-8,240.0,Syracuse,22875000.0,Basketball
35,Cleanthony Early,New York Knicks,11.0,USA,SF,25.0,6-8,210.0,Wichita State,845059.0,Basketball
36,Langston Galloway,New York Knicks,2.0,USA,SG,24.0,6-2,200.0,Saint Joseph's,845059.0,Basketball
...,...,...,...,...,...,...,...,...,...,...,...
422,Cameron Payne,Oklahoma City Thunder,22.0,USA,PG,21.0,6-3,185.0,Murray State,2021520.0,Basketball
423,Andre Roberson,Oklahoma City Thunder,21.0,USA,SG,24.0,6-7,210.0,Colorado,1210800.0,Basketball
424,Kyle Singler,Oklahoma City Thunder,5.0,USA,SF,28.0,6-8,228.0,Duke,4500000.0,Basketball
425,Dion Waiters,Oklahoma City Thunder,3.0,USA,SG,24.0,6-4,220.0,Syracuse,5138430.0,Basketball
426,Russell Westbrook,Oklahoma City Thunder,0.0,USA,PG,27.0,6-3,200.0,UCLA,16744218.0,Basketball
427,Cliff Alexander,Portland Trail Blazers,34.0,USA,PF,20.0,6-8,240.0,Kansas,525093.0,Basketball
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,USA,SF,25.0,6-9,215.0,Wake Forest,8042895.0,Basketball
429,Pat Connaughton,Portland Trail Blazers,5.0,USA,SG,23.0,6-5,206.0,Notre Dame,625093.0,Basketball
430,Allen Crabbe,Portland Trail Blazers,23.0,USA,SG,24.0,6-6,210.0,California,947276.0,Basketball
431,Ed Davis,Portland Trail Blazers,17.0,USA,C,27.0,6-10,240.0,North Carolina,6980802.0,Basketball
432,Maurice Harkless,Portland Trail Blazers,4.0,USA,SF,23.0,6-9,215.0,St. John's,2894059.0,Basketball
433,Gerald Henderson,Portland Trail Blazers,9.0,USA,SG,28.0,6-5,215.0,Duke,6000000.0,Basketball
434,Chris Kaman,Portland Trail Blazers,35.0,USA,C,34.0,7-0,265.0,Central Michigan,5016000.0,Basketball
435,Meyers Leonard,Portland Trail Blazers,11.0,USA,PF,24.0,7-1,245.0,Illinois,3075880.0,Basketball
436,Damian Lillard,Portland Trail Blazers,0.0,USA,PG,25.0,6-3,195.0,Weber State,4236287.0,Basketball
437,C.J. McCollum,Portland Trail Blazers,3.0,USA,SG,24.0,6-4,200.0,Lehigh,2525160.0,Basketball
438,Luis Montero,Portland Trail Blazers,44.0,USA,SG,23.0,6-7,185.0,Westchester CC,525093.0,Basketball
439,Mason Plumlee,Portland Trail Blazers,24.0,USA,C,26.0,6-11,235.0,Duke,1415520.0,Basketball
440,Brian Roberts,Portland Trail Blazers,2.0,USA,PG,30.0,6-1,173.0,Dayton,2854940.0,Basketball
441,Noah Vonleh,Portland Trail Blazers,21.0,USA,PF,20.0,6-9,240.0,Indiana,2637720.0,Basketball
442,Trevor Booker,Utah Jazz,33.0,USA,PF,28.0,6-8,228.0,Clemson,4775000.0,Basketball
443,Trey Burke,Utah Jazz,3.0,USA,PG,23.0,6-1,191.0,Michigan,2658240.0,Basketball
444,Alec Burks,Utah Jazz,10.0,USA,SG,24.0,6-6,214.0,Colorado,9463484.0,Basketball
446,Derrick Favors,Utah Jazz,15.0,USA,PF,24.0,6-10,265.0,Georgia Tech,12000000.0,Basketball
448,Gordon Hayward,Utah Jazz,20.0,USA,SF,26.0,6-8,226.0,Butler,15409570.0,Basketball
449,Rodney Hood,Utah Jazz,5.0,USA,SG,23.0,6-8,206.0,Duke,1348440.0,Basketball
451,Chris Johnson,Utah Jazz,23.0,USA,SF,26.0,6-6,206.0,Dayton,981348.0,Basketball
452,Trey Lyles,Utah Jazz,41.0,USA,PF,20.0,6-10,234.0,Kentucky,2239800.0,Basketball
453,Shelvin Mack,Utah Jazz,8.0,USA,PG,26.0,6-3,203.0,Butler,2433333.0,Basketball
456,Jeff Withey,Utah Jazz,24.0,USA,C,26.0,7-0,231.0,Kansas,947276.0,Basketball

In [35]:
nba = pd.read_csv('nba.csv')

In [38]:
nba['Salary'].fillna(0, inplace=True)
nba['College'].fillna('None', inplace=True)
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,None,5000000.0

In [41]:
nba['Salary'] = nba['Salary'].astype('int')

In [42]:
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary        int32
dtype: object

In [44]:
nba['Position'].nunique()

5

In [45]:
nba['Position'] = nba['Position'].astype('category')

In [46]:
nba.dtypes

Name          object
Team          object
Number       float64
Position    category
Age          float64
Height        object
Weight       float64
College       object
Salary         int32
dtype: object

In [48]:
nba.sort_values(['Team', 'Name'])

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000
318,Dennis Schroder,Atlanta Hawks,17.0,PG,22.0,6-1,172.0,None,1763400
323,Jeff Teague,Atlanta Hawks,0.0,PG,27.0,6-2,186.0,Wake Forest,8000000
309,Kent Bazemore,Atlanta Hawks,24.0,SF,26.0,6-5,201.0,Old Dominion,2000000
311,Kirk Hinrich,Atlanta Hawks,12.0,SG,35.0,6-4,190.0,Kansas,2854940
313,Kris Humphries,Atlanta Hawks,43.0,PF,31.0,6-9,235.0,Minnesota,1000000
314,Kyle Korver,Atlanta Hawks,26.0,SG,35.0,6-7,212.0,Creighton,5746479
317,Lamar Patterson,Atlanta Hawks,13.0,SG,24.0,6-5,225.0,Pittsburgh,525093
316,Mike Muscala,Atlanta Hawks,31.0,PF,24.0,6-11,240.0,Bucknell,947276
319,Mike Scott,Atlanta Hawks,32.0,PF,27.0,6-8,237.0,Virginia,3333333
315,Paul Millsap,Atlanta Hawks,4.0,PF,31.0,6-8,246.0,Louisiana Tech,18671659
320,Thabo Sefolosha,Atlanta Hawks,25.0,SF,32.0,6-7,220.0,None,4000000
321,Tiago Splitter,Atlanta Hawks,11.0,C,31.0,6-11,245.0,None,9756250
310,Tim Hardaway Jr.,Atlanta Hawks,10.0,SG,24.0,6-6,205.0,Michigan,1304520
322,Walter Tavares,Atlanta Hawks,22.0,C,24.0,7-3,260.0,None,1000000
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,None,12000000
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,None,5000000
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975
...,...,...,...,...,...,...,...,...,...
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,None,3777720
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,None,2050000
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,None,900000
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,None,1175880
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,None,2900000
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800
368,Alan Anderson,Washington Wizards,6.0,SG,33.0,6-6,220.0,Michigan State,4000000
369,Bradley Beal,Washington Wizards,3.0,SG,22.0,6-5,207.0,Florida,5694674
372,Drew Gooden,Washington Wizards,90.0,PF,34.0,6-10,250.0,Kansas,3300000
380,Garrett Temple,Washington Wizards,17.0,SG,30.0,6-6,195.0,LSU,1100602
374,JJ Hickson,Washington Wizards,21.0,C,27.0,6-9,242.0,North Carolina State,273038
370,Jared Dudley,Washington Wizards,1.0,SF,30.0,6-7,225.0,Boston College,4375000
371,Jarell Eddie,Washington Wizards,8.0,SG,24.0,6-7,218.0,Virginia Tech,561716
382,John Wall,Washington Wizards,2.0,PG,25.0,6-4,195.0,Kentucky,15851950
377,Kelly Oubre Jr.,Washington Wizards,12.0,SF,20.0,6-7,205.0,Kansas,1920240
373,Marcin Gortat,Washington Wizards,13.0,C,32.0,6-11,240.0,None,11217391
381,Marcus Thornton,Washington Wizards,15.0,SF,29.0,6-4,205.0,LSU,200600
376,Markieff Morris,Washington Wizards,5.0,PF,26.0,6-10,245.0,Kansas,8000000
375,Nene Hilario,Washington Wizards,42.0,C,33.0,6-11,250.0,None,13000000
378,Otto Porter Jr.,Washington Wizards,22.0,SF,23.0,6-8,198.0,Georgetown,4662960
379,Ramon Sessions,Washington Wizards,7.0,PG,30.0,6-3,190.0,Nevada,2170465
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,0

In [51]:
nba['Salary'].rank(ascending=False).astype('int')

0       97
1      110
2      452
3      322
4      147
5       57
6      316
7      253
8      272
9      190
10     233
11     109
12     191
13     274
14     231
15     191
16     393
17     288
18     300
19     116
20     282
21     439
22     288
23      11
24     325
25     367
26     347
27     367
28     367
29      63
      ...
428     90
429    406
430    367
431    108
432    216
433    121
434    143
435    206
436    164
437    234
438    415
439    295
440    220
441    230
442    151
443    229
444     78
445    181
446     57
447    315
448     32
449    299
450    262
451    347
452    250
453    241
454    383
455    214
456    367
457    452
Name: Salary, Length: 458, dtype: int32